version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crypto_exchange
    ports:
      - "3307:3306"       
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_dev
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db       
      PMA_PORT: 3306

  backend:
    build: .
    container_name: backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: rootpassword
      DB_NAME: crypto_exchange
    depends_on:
      - db
    command: ["node", "app.js"] 
volumes:
  db_data:
